"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-20 16:18:42.991734+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_groups',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_muscle_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_muscle_groups_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_unit', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('body_measurements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('measured_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arm_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thigh_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neck_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_measurements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurements'))
    )
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('primary_muscle_id', sa.BigInteger(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_exercises_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_muscle_id'], ['muscle_groups.id'], name=op.f('fk_exercises_primary_muscle_id_muscle_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_table('routines',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    op.create_table('goals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('goal_type', sa.Text(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_goals_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_table('routine_days',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('routine_id', sa.BigInteger(), nullable=False),
    sa.Column('day_order', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_routine_days_routine_id_routines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_days')),
    sa.UniqueConstraint('routine_id', 'day_order', name='routine_day_order')
    )
    op.create_table('routine_day_exercises',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('routine_day_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=True),
    sa.Column('target_sets', sa.SmallInteger(), nullable=True),
    sa.Column('target_reps_min', sa.SmallInteger(), nullable=True),
    sa.Column('target_reps_max', sa.SmallInteger(), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_routine_day_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['routine_day_id'], ['routine_days.id'], name=op.f('fk_routine_day_exercises_routine_day_id_routine_days'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_day_exercises'))
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('routine_day_id', sa.BigInteger(), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bodyweight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_day_id'], ['routine_days.id'], name=op.f('fk_workout_sessions_routine_day_id_routine_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions'))
    )
    op.create_table('set_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_set_logs_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('fk_set_logs_session_id_workout_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_logs'))
    )
    # ### end Alembic commands ###

    # --- Índices sobre FKs frecuentes (joins / analítica) ---
    op.create_index("ix_exercises_owner_id", "exercises", ["owner_id"])
    op.create_index(
        "ix_exercises_primary_muscle_id", "exercises", ["primary_muscle_id"]
    )
    op.create_index("ix_routines_user_id", "routines", ["user_id"])
    op.create_index(
        "ix_routine_days_routine_id", "routine_days", ["routine_id"]
    )
    op.create_index(
        "ix_rde_routine_day_id", "routine_day_exercises", ["routine_day_id"]
    )
    op.create_index(
        "ix_workout_sessions_user_id", "workout_sessions", ["user_id"]
    )
    op.create_index(
        "ix_workout_sessions_routine_day_id",
        "workout_sessions",
        ["routine_day_id"],
    )
    op.create_index("ix_set_logs_session_id", "set_logs", ["session_id"])
    op.create_index("ix_set_logs_exercise_id", "set_logs", ["exercise_id"])
    op.create_index(
        "ix_body_measurements_user_id", "body_measurements", ["user_id"]
    )
    op.create_index("ix_goals_user_id", "goals", ["user_id"])
    op.create_index(
        "ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"]
    )

    # --- Vista personal_records ---
    # Mejor serie de trabajo (mayor 1RM estimado, fórmula de Epley) por
    # usuario / ejercicio / día. Alimenta las gráficas de sobrecarga progresiva.
    op.execute(
        """
        CREATE VIEW personal_records AS
        SELECT DISTINCT ON (ws.user_id, sl.exercise_id, performed_date)
            ws.user_id,
            sl.exercise_id,
            (ws.performed_at AT TIME ZONE 'UTC')::date AS performed_date,
            sl.weight,
            sl.reps,
            sl.rpe,
            ROUND(sl.weight * (1 + sl.reps::numeric / 30), 2) AS est_1rm
        FROM set_logs sl
        JOIN workout_sessions ws ON ws.id = sl.session_id
        WHERE sl.is_warmup = false
        ORDER BY ws.user_id, sl.exercise_id, performed_date, est_1rm DESC;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS personal_records")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_logs')
    op.drop_table('workout_sessions')
    op.drop_table('routine_day_exercises')
    op.drop_table('routine_days')
    op.drop_table('goals')
    op.drop_table('routines')
    op.drop_table('refresh_tokens')
    op.drop_table('exercises')
    op.drop_table('body_measurements')
    op.drop_table('users')
    op.drop_table('muscle_groups')
    # ### end Alembic commands ###
